package model

import "time"

// Category groups related habits together
type Category struct {
	ID        int64
	Name      string
	Color     string // Hex color code (e.g., "#FF5733")
	Emoji     string // User-selected emoji (e.g., "🏃", "💪", "📚")
	CreatedAt time.Time
}

// Default category colors for quick selection
var DefaultColors = []string{
	"#FF6B6B", // Red
	"#4ECDC4", // Teal
	"#45B7D1", // Blue
	"#96CEB4", // Green
	"#FFEAA7", // Yellow
	"#DDA0DD", // Plum
	"#98D8C8", // Mint
	"#F7DC6F", // Gold
}

// DefaultColorEmojis maps to each color for visual distinction
var DefaultColorEmojis = []string{
	"🔴", // Red
	"🩵", // Teal
	"🔵", // Blue
	"🟢", // Green
	"🟡", // Yellow
	"🟣", // Plum
	"🩶", // Mint
	"🟠", // Gold/Orange
}

// CommonEmojis provides a comprehensive list of emojis for category selection
var CommonEmojis = []string{
	// Smileys & Emotion
	"😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃", "😉", "😊", "😇",
	"🥰", "😍", "🤩", "😘", "😗", "😚", "😙", "🥲", "😋", "😛", "😜", "🤪", "😝",
	"🤑", "🤗", "🤭", "🤫", "🤔", "🤐", "🤨", "😐", "😑", "😶", "😏", "😒", "🙄",
	"😬", "🤥", "😌", "😔", "😪", "🤤", "😴", "😷", "🤒", "🤕", "🤢", "🤮", "🤧",
	"🥵", "🥶", "😶‍🌫️", "😵", "🤯", "🤠", "🥳", "🥸", "😎", "🤓", "🧐", "😕", "😟",
	"🙁", "☹️", "😮", "😯", "😲", "😳", "🥺", "😦", "😧", "😨", "😰", "😥", "😢",
	"😭", "😱", "😖", "😣", "😞", "😓", "😩", "😫", "🥱", "😤", "😡", "😠", "🤬",
	"💀", "☠️", "💩", "🤡", "👹", "👺", "👻", "👽", "👾", "🤖",

	// Hearts & Love
	"❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❤️‍🔥", "❤️‍🩹",
	"💕", "💞", "💓", "💗", "💖", "💘", "💝", "💟",

	// People & Body
	"👋", "🤚", "🖐️", "✋", "🖖", "👌", "🤌", "🤏", "✌️", "🤞", "🤟", "🤘", "🤙",
	"👈", "👉", "👆", "👇", "☝️", "👍", "👎", "✊", "👊", "🤛", "🤜", "👏", "🙌",
	"👐", "🤲", "🤝", "🙏", "✍️", "💅", "🤳", "💪", "🦾", "🦿", "🦵", "🦶",
	"👂", "🦻", "👃", "🧠", "🫀", "🫁", "🦷", "🦴", "👀", "👁️", "👅", "👄",

	// Animals & Nature
	"🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🐻", "🐼", "🐨", "🐯", "🦁", "🐮", "🐷",
	"🐸", "🐵", "🙈", "🙉", "🙊", "🐔", "🐧", "🐦", "🐤", "🦆", "🦅", "🦉", "🦇",
	"🐺", "🐗", "🐴", "🦄", "🐝", "🐛", "🦋", "🐌", "🐞", "🐜", "🦟", "🦗", "🕷️",
	"🦂", "🐢", "🐍", "🦎", "🦖", "🦕", "🐙", "🦑", "🦐", "🦞", "🦀", "🐡", "🐠",
	"🐟", "🐬", "🐳", "🐋", "🦈", "🐊", "🐅", "🐆", "🦓", "🦍", "🦧", "🐘", "🦛",
	"🦏", "🐪", "🐫", "🦒", "🦘", "🐃", "🐂", "🐄", "🐎", "🐖", "🐏", "🐑", "🦙",
	"🐐", "🦌", "🐕", "🐩", "🦮", "🐈", "🐓", "🦃", "🦚", "🦜", "🦢", "🦩", "🕊️",
	"🐇", "🦝", "🦨", "🦡", "🦫", "🦦", "🦥", "🐁", "🐀", "🐿️", "🦔",

	// Plants & Nature
	"💐", "🌸", "💮", "🏵️", "🌹", "🥀", "🌺", "🌻", "🌼", "🌷", "🌱", "🪴", "🌲",
	"🌳", "🌴", "🌵", "🌾", "🌿", "☘️", "🍀", "🍁", "🍂", "🍃", "🍄", "🌰", "🦀",

	// Food & Drink
	"🍇", "🍈", "🍉", "🍊", "🍋", "🍌", "🍍", "🥭", "🍎", "🍏", "🍐", "🍑", "🍒",
	"🍓", "🥝", "🍅", "🥥", "🥑", "🍆", "🥔", "🥕", "🌽", "🌶️", "🥒", "🥬", "🥦",
	"🧄", "🧅", "🍄", "🥜", "🌰", "🍞", "🥐", "🥖", "🥨", "🥯", "🥞", "🧇", "🧀",
	"🍖", "🍗", "🥩", "🥓", "🍔", "🍟", "🍕", "🌭", "🥪", "🌮", "🌯", "🥙", "🧆",
	"🥚", "🍳", "🥘", "🍲", "🥣", "🥗", "🍿", "🧈", "🧂", "🥫",
	"🍱", "🍘", "🍙", "🍚", "🍛", "🍜", "🍝", "🍠", "🍢", "🍣", "🍤", "🍥", "🥮",
	"🍡", "🥟", "🥠", "🥡", "🦀", "🦞", "🦐", "🦑", "🦪",
	"🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁", "🥧", "🍫", "🍬", "🍭", "🍮",
	"🍯", "🍼", "🥛", "☕", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹", "🍺", "🍻", "🥂",
	"🥃", "🥤", "🧃", "🧉", "🧊",

	// Travel & Places
	"🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐", "🚚", "🚛", "🚜",
	"🦯", "🦽", "🦼", "🛴", "🚲", "🛵", "🏍️", "🛺", "🚨", "🚔", "🚍", "🚘", "🚖",
	"🚡", "🚠", "🚟", "🚃", "🚋", "🚞", "🚝", "🚄", "🚅", "🚈", "🚂", "🚆", "🚇",
	"🚊", "🚉", "✈️", "🛫", "🛬", "🛩️", "💺", "🛰️", "🚀", "🛸", "🚁", "🛶", "⛵",
	"🚤", "🛥️", "🛳️", "⛴️", "🚢", "⚓", "⛽", "🚧", "🚦", "🚥", "🗺️", "🗿", "🗽",
	"🏰", "🏯", "🏟️", "🎡", "🎢", "🎠", "⛲", "⛱️", "🏖️", "🏝️", "🏜️", "🌋", "⛰️",
	"🏔️", "🗻", "🏕️", "⛺", "🏠", "🏡", "🏘️", "🏚️", "🏗️", "🏭", "🏢", "🏬", "🏣",
	"🏤", "🏥", "🏦", "🏨", "🏪", "🏫", "🏩", "💒", "🏛️", "⛪", "🕌", "🕍", "🛕",

	// Activities
	"⚽", "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "🎱", "🪀", "🏓", "🏸",
	"🏒", "🏑", "🥍", "🏏", "🥅", "⛳", "🪁", "🏹", "🎣", "🤿", "🥊", "🥋", "🎽",
	"🛹", "🛼", "🛷", "⛸️", "🥌", "🎿", "⛷️", "🏂", "🪂", "🏋️", "🤼", "🤸", "🤺",
	"⛹️", "🤾", "🏌️", "🏇", "🧘", "🏊", "🚴", "🚵", "🧗", "🤹",
	"🎪", "🎭", "🎨", "🎬", "🎤", "🎧", "🎼", "🎹", "🥁", "🎷", "🎺", "🎸", "🪕",
	"🎻", "🎲", "♟️", "🎯", "🎳", "🎮", "🎰", "🧩",

	// Objects
	"⌚", "📱", "📲", "💻", "⌨️", "🖥️", "🖨️", "🖱️", "🖲️", "🕹️", "🗜️", "💽", "💾",
	"💿", "📀", "📼", "📷", "📸", "📹", "🎥", "📽️", "🎞️", "📞", "☎️", "📟", "📠",
	"📺", "📻", "🎙️", "🎚️", "🎛️", "🧭", "⏱️", "⏲️", "⏰", "🕰️", "⌛", "⏳", "📡",
	"🔋", "🔌", "💡", "🔦", "🕯️", "🪔", "🧯", "🛢️", "💸", "💵", "💴", "💶", "💷",
	"💰", "💳", "💎", "⚖️", "🧰", "🔧", "🔨", "⚒️", "🛠️", "⛏️", "🔩", "⚙️", "🧱",
	"⛓️", "🧲", "🔫", "💣", "🧨", "🪓", "🔪", "🗡️", "⚔️", "🛡️", "🚬", "⚰️", "⚱️",
	"🏺", "🔮", "📿", "🧿", "💈", "⚗️", "🔭", "🔬", "🕳️", "🩹", "🩺", "💊", "💉",
	"🩸", "🧬", "🦠", "🧫", "🧪", "🌡️", "🧹", "🧺", "🧻", "🚽", "🚰", "🚿", "🛁",
	"🛀", "🧼", "🪒", "🧽", "🧴", "🛎️", "🔑", "🗝️", "🚪", "🪑", "🛋️", "🛏️", "🛌",
	"🧸", "🖼️", "🛍️", "🛒", "🎁", "🎈", "🎏", "🎀", "🎊", "🎉", "🎎", "🏮", "🎐",
	"🧧", "✉️", "📩", "📨", "📧", "💌", "📥", "📤", "📦", "🏷️", "📪", "📫", "📬",
	"📭", "📮", "📯", "📜", "📃", "📄", "📑", "🧾", "📊", "📈", "📉", "🗒️", "🗓️",
	"📆", "📅", "🗑️", "📇", "🗃️", "🗳️", "🗄️", "📋", "📁", "📂", "🗂️", "🗞️", "📰",
	"📓", "📔", "📒", "📕", "📗", "📘", "📙", "📚", "📖", "🔖", "🧷", "🔗", "📎",
	"🖇️", "📐", "📏", "🧮", "📌", "📍", "✂️", "🖊️", "🖋️", "✒️", "🖌️", "🖍️", "📝",
	"✏️", "🔍", "🔎", "🔏", "🔐", "🔒", "🔓",

	// Symbols
	"❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔", "❣️", "💕", "💞",
	"💓", "💗", "💖", "💘", "💝", "💟", "☮️", "✝️", "☪️", "🕉️", "☸️", "✡️", "🔯",
	"🕎", "☯️", "☦️", "🛐", "⛎", "♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐",
	"♑", "♒", "♓", "🆔", "⚛️", "🉑", "☢️", "☣️", "📴", "📳", "🈶", "🈚", "🈸",
	"🈺", "🈷️", "✴️", "🆚", "💮", "🉐", "㊙️", "㊗️", "🈴", "🈵", "🈹", "🈲", "🅰️",
	"🅱️", "🆎", "🆑", "🅾️", "🆘", "❌", "⭕", "🛑", "⛔", "📛", "🚫", "💯", "💢",
	"♨️", "🚷", "🚯", "🚳", "🚱", "🔞", "📵", "🚭", "❗", "❕", "❓", "❔", "‼️",
	"⁉️", "🔅", "🔆", "〽️", "⚠️", "🚸", "🔱", "⚜️", "🔰", "♻️", "✅", "🈯", "💹",
	"❇️", "✳️", "❎", "🌐", "💠", "Ⓜ️", "🌀", "💤", "🏧", "🚾", "♿", "🅿️", "🈳",
	"🈂️", "🛂", "🛃", "🛄", "🛅", "🚹", "🚺", "🚼", "🚻", "🚮", "🎦", "📶", "🈁",
	"🔣", "ℹ️", "🔤", "🔡", "🔠", "🆖", "🆗", "🆙", "🆒", "🆕", "🆓", "0️⃣", "1️⃣",
	"2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟", "🔢", "#️⃣", "*️⃣", "⏏️",
	"▶️", "⏸️", "⏯️", "⏹️", "⏺️", "⏭️", "⏮️", "⏩", "⏪", "⏫", "⏬", "◀️", "🔼", "🔽",
	"➡️", "⬅️", "⬆️", "⬇️", "↗️", "↘️", "↙️", "↖️", "↕️", "↔️", "↪️", "↩️", "⤴️",
	"⤵️", "🔀", "🔁", "🔂", "🔄", "🔃", "🎵", "🎶", "➕", "➖", "➗", "✖️", "♾️",
	"💲", "💱", "™️", "©️", "®️", "〰️", "➰", "➿", "🔚", "🔙", "🔛", "🔝", "🔜",
	"✔️", "☑️", "🔘", "🔴", "🟠", "🟡", "🟢", "🔵", "🟣", "⚫", "⚪", "🟤", "🔺",
	"🔻", "🔸", "🔹", "🔶", "🔷", "🔳", "🔲", "▪️", "▫️", "◾", "◽", "◼️", "◻️",
	"🟥", "🟧", "🟨", "🟩", "🟦", "🟪", "⬛", "⬜", "🟫", "🔈", "🔇", "🔉", "🔊",
	"🔔", "🔕", "📣", "📢", "👁️‍🗨️", "💬", "💭", "🗯️", "♠️", "♣️", "♥️", "♦️", "🃏",
	"🎴", "🀄", "🕐", "🕑", "🕒", "🕓", "🕔", "🕕", "🕖", "🕗", "🕘", "🕙", "🕚",
	"🕛", "🕜", "🕝", "🕞", "🕟", "🕠", "🕡", "🕢", "🕣", "🕤", "🕥", "🕦", "🕧",

	// Weather & Sky
	"🌍", "🌎", "🌏", "🌐", "🗺️", "🗾", "🧭", "🏔️", "⛰️", "🌋", "🗻", "🏕️", "🏖️",
	"🏜️", "🏝️", "🏞️", "🏟️", "🏛️", "🏗️", "🧱", "🏘️", "🏚️", "🏠", "🏡", "🏢",
	"🏣", "🏤", "🏥", "🏦", "🏨", "🏩", "🏪", "🏫", "🏬", "🏭", "🏯", "🏰", "💒",
	"🗼", "🗽", "⛪", "🕌", "🛕", "🕍", "⛩️", "🕋", "⛲", "⛺", "🌁", "🌃", "🏙️",
	"🌄", "🌅", "🌆", "🌇", "🌉", "♨️", "🎠", "🎡", "🎢", "💈", "🎪",
	"🌈", "🌤️", "⛅", "🌥️", "☁️", "🌦️", "🌧️", "⛈️", "🌩️", "🌨️", "❄️", "☃️", "⛄",
	"🌬️", "💨", "💧", "💦", "☔", "☂️", "🌊", "🌫️", "🌪️", "🌀", "🌈", "🌂",
	"☀️", "🌝", "🌛", "🌜", "🌚", "🌕", "🌖", "🌗", "🌘", "🌑", "🌒", "🌓", "🌔",
	"🌙", "🌎", "🌍", "🌏", "🪐", "💫", "⭐", "🌟", "✨", "⚡", "☄️", "💥", "🔥",
	"🌪️", "🌈", "☀️", "🌤️", "⛅", "🌥️", "☁️", "🌦️", "🌧️", "⛈️", "🌩️", "🌨️",
}

// EmojiKeywords maps emojis to searchable keywords
var EmojiKeywords = map[string]string{
	// Smileys & Emotion
	"😀": "happy smile grin face joy glad",
	"😃": "happy smile big grin face joy",
	"😄": "happy smile laugh joy face",
	"😁": "grin happy face smile joy",
	"😆": "laugh happy smile grin joy squint",
	"😅": "sweat smile nervous relief happy",
	"🤣": "rofl laugh rolling floor funny hilarious",
	"😂": "tears joy laugh crying funny happy",
	"🙂": "smile happy slightly content",
	"😉": "wink flirt face playful",
	"😊": "smile blush happy face warm",
	"😇": "angel halo innocent good smile",
	"🥰": "love hearts smile adore crush",
	"😍": "love heart eyes smile crush adore",
	"🤩": "star eyes amazed excited wow",
	"😘": "kiss love heart blow face",
	"😋": "yum delicious food tasty tongue",
	"😎": "cool sunglasses confident stylish",
	"🤓": "nerd geek glasses smart studious",
	"🤔": "thinking hmm curious ponder wonder",
	"😴": "sleep tired zzz rest sleepy",
	"😌": "peace calm relax meditation happy",
	"😭": "cry tears sad upset sobbing",
	"😱": "scared scream shock fear horror",
	"😡": "angry mad rage furious upset",
	"🤯": "mind blown shocked amazed explode",
	"🥳": "party celebration birthday hat fun",
	"💀": "skull death dead bones",
	"💩": "poop shit pile funny",
	"👻": "ghost spirit halloween spooky boo",
	"👽": "alien ufo space extraterrestrial",
	"🤖": "robot bot ai machine android",

	// Hearts
	"❤️": "love heart care relationship family red",
	"🧡": "orange heart love care",
	"💛": "yellow heart love care happy",
	"💚": "green heart love care nature",
	"💙": "blue heart love care trust",
	"💜": "purple heart love care magic",
	"🖤": "black heart love dark sad",
	"🤍": "white heart love pure clean",
	"💔": "broken heart sad heartbreak breakup",
	"💕": "two hearts love romance pink",
	"💖": "sparkling heart love shine glitter",
	"💝": "heart gift love present valentine",

	// People & Body
	"👋": "wave hello hi goodbye hand",
	"🤚": "raised hand back stop high five",
	"👌": "ok okay good perfect fine hand",
	"✌️": "peace victory two fingers hand",
	"🤞": "crossed fingers luck hope wish",
	"👍": "thumbs up good yes like agree",
	"👎": "thumbs down bad no dislike disagree",
	"✊": "fist punch power solidarity raised",
	"👏": "clap applause congrats well done bravo",
	"🙌": "celebration hands raised hooray yay",
	"🙏": "pray thank namaste please gratitude",
	"💪": "fitness muscle strength workout gym exercise flex",
	"🦾": "mechanical arm prosthetic robot strength",
	"👀": "eyes look see watch stare",
	"🧠": "brain thinking learning mental mind smart",

	// Animals
	"🐶": "dog puppy pet animal cute",
	"🐱": "cat kitten pet animal cute",
	"🐭": "mouse rat small animal rodent",
	"🐰": "rabbit bunny cute pet animal",
	"🦊": "fox animal wild cute clever",
	"🐻": "bear animal wild cute teddy",
	"🐼": "panda bear animal cute bamboo",
	"🐨": "koala bear animal cute australia",
	"🐯": "tiger animal wild cat striped",
	"🦁": "lion king animal wild cat",
	"🐮": "cow animal farm milk moo",
	"🐷": "pig animal farm cute oink",
	"🐸": "frog animal toad green ribbit",
	"🐵": "monkey animal cute funny",
	"🐔": "chicken animal bird farm rooster",
	"🐧": "penguin bird animal cute waddle",
	"🐦": "bird animal fly tweet chirp",
	"🦆": "duck bird animal water quack",
	"🦅": "eagle bird animal majestic fly",
	"🦉": "owl bird animal wise night",
	"🐝": "bee insect honey buzz fly",
	"🦋": "butterfly insect beautiful fly",
	"🐙": "octopus sea ocean animal tentacle",
	"🦈": "shark fish ocean dangerous predator",
	"🐬": "dolphin ocean animal smart cute",
	"🐳": "whale ocean animal large blue",
	"🐘": "elephant animal large trunk memory",
	"🦒": "giraffe animal tall neck spots",
	"🐕": "dog pet animal loyal friend",
	"🐈": "cat pet animal independent cute",
	"🦄": "unicorn magical fantasy rainbow horse",

	// Plants & Nature
	"💐": "bouquet flowers gift nature pretty",
	"🌸": "cherry blossom flower spring pink",
	"🌹": "rose flower love red romantic",
	"🌻": "sunflower flower yellow summer happy",
	"🌼": "flower blossom daisy nature pretty",
	"🌷": "tulip flower spring pretty",
	"🌱": "plant seedling grow nature garden vegan",
	"🪴": "potted plant gardening grow nature indoor",
	"🌲": "evergreen tree pine christmas nature",
	"🌳": "tree nature deciduous forest green",
	"🌴": "palm tree tropical beach island",
	"🌵": "cactus desert plant succulent",
	"🌾": "sheaf rice grain wheat harvest",
	"🌿": "herb leaf plant nature green",
	"🍀": "four leaf clover luck lucky irish",
	"🍁": "maple leaf fall autumn canada",
	"🍂": "fallen leaf autumn fall nature",
	"🍃": "leaf blowing wind nature flutter",

	// Food & Drink
	"🍇": "grapes fruit purple food healthy",
	"🍉": "watermelon fruit summer refreshing",
	"🍊": "orange tangerine fruit citrus vitamin",
	"🍋": "lemon fruit citrus sour yellow",
	"🍌": "banana fruit yellow potassium healthy",
	"🍍": "pineapple fruit tropical yellow sweet",
	"🍎": "apple fruit healthy food nutrition red",
	"🍓": "strawberry fruit red sweet berry",
	"🥝": "kiwi fruit green tropical healthy",
	"🍅": "tomato fruit vegetable red sauce",
	"🥑": "avocado healthy food nutrition green toast",
	"🥕": "carrot vegetable orange healthy",
	"🌽": "corn maize vegetable yellow",
	"🥦": "broccoli vegetable green healthy",
	"🥒": "cucumber vegetable green fresh salad",
	"🥬": "leafy green vegetable lettuce salad",
	"🧄": "garlic vegetable flavor cooking",
	"🧅": "onion vegetable cooking flavor",
	"🍄": "mushroom fungus food vegetable",
	"🍞": "bread loaf food carbs breakfast",
	"🥐": "croissant bread french pastry breakfast",
	"🥖": "baguette bread french long",
	"🧀": "cheese dairy food yellow",
	"🍖": "meat bone food protein steak",
	"🍗": "poultry leg chicken turkey food",
	"🥩": "cut meat steak beef food",
	"🥓": "bacon breakfast meat pork",
	"🍔": "hamburger burger food fast meal",
	"🍟": "fries french potato food fast",
	"🍕": "pizza italian food cheese slice",
	"🌭": "hot dog sausage food american",
	"🥪": "sandwich food lunch bread",
	"🌮": "taco mexican food shell meat",
	"🌯": "burrito mexican food wrap tortilla",
	"🥗": "salad healthy food nutrition vegetable green",
	"🍜": "noodles ramen steaming bowl food",
	"🍝": "pasta spaghetti italian food",
	"🍱": "bento box japanese lunch food",
	"🍣": "sushi japanese raw fish food",
	"🦐": "shrimp seafood prawn food",
	"🍦": "soft ice cream dessert sweet",
	"🍨": "ice cream dessert cold sweet",
	"🍩": "doughnut donut sweet dessert breakfast",
	"🍪": "cookie sweet dessert bake snack",
	"🎂": "birthday cake celebration dessert party",
	"🍰": "cake shortcake dessert sweet slice",
	"🧁": "cupcake sweet dessert muffin",
	"🍫": "chocolate bar sweet candy dessert",
	"🍬": "candy sweet sugar treat",
	"🍯": "honey pot sweet bee natural",
	"☕": "coffee hot beverage morning espresso cafe",
	"🍵": "tea drink beverage hot green",
	"🥛": "milk drink beverage dairy glass",
	"🍷": "wine glass red alcohol drink",
	"🍺": "beer mug alcohol drink cheers",
	"🥤": "drink beverage cup soda water",
	"🧃": "juice box drink beverage fruit",

	// Travel & Places
	"🚗": "car automobile vehicle drive transport",
	"🚕": "taxi cab car ride transport",
	"🚙": "suv car vehicle family transport",
	"🚌": "bus public transport vehicle",
	"🚎": "trolleybus bus electric public transport",
	"🏎️": "race car fast sports vehicle",
	"🚓": "police car cop law enforcement",
	"🚑": "ambulance emergency medical vehicle",
	"🚒": "fire engine truck emergency firefighter",
	"🚐": "minibus van vehicle transport",
	"🚚": "delivery truck vehicle transport cargo",
	"🚛": "semi truck lorry transport cargo",
	"🚜": "tractor farm vehicle agricultural",
	"🚲": "bicycle bike cycle pedal transport",
	"🏍️": "motorcycle bike motor vehicle",
	"✈️": "airplane plane fly travel transport",
	"🚀": "rocket space launch shuttle nasa",
	"🚁": "helicopter chopper fly transport",
	"🛶": "canoe boat kayak paddle water",
	"⛵": "sailboat boat sail ocean yacht",
	"🚤": "speedboat boat fast water motor",
	"🚢": "ship boat cruise ocean vessel",
	"⚓": "anchor ship boat sea marine",
	"🏠": "home house living space residence",
	"🏡": "house garden home suburban residence",
	"🏢": "office building work business corporate",
	"🏥": "hospital medical health doctor clinic",
	"🏦": "bank money finance atm financial",
	"🏨": "hotel accommodation travel stay lodging",
	"🏪": "convenience store shop 24/7 market",
	"🏫": "school education learning student class",
	"🏬": "department store shopping mall retail",
	"🏭": "factory industry manufacturing plant",
	"⛪": "church religion christian worship",
	"🏰": "castle fort medieval royal palace",
	"🗽": "statue liberty new york freedom",
	"🎡": "ferris wheel carnival fair amusement",
	"🎢": "roller coaster thrill ride amusement",
	"⛺": "tent camping outdoor camp adventure",
	"🏖️": "beach umbrella vacation sand ocean",
	"🏝️": "desert island tropical paradise beach",
	"⛰️": "mountain peak nature hiking climb",
	"🌋": "volcano eruption lava mountain",
	"🏕️": "camping tent outdoor nature adventure",

	// Activities & Sports
	"⚽": "soccer football sport ball game kick",
	"🏀": "basketball sport ball game hoop",
	"🏈": "american football sport game tackle",
	"⚾": "baseball sport ball game bat",
	"🎾": "tennis sport ball game racket court",
	"🏐": "volleyball sport ball game beach",
	"🏉": "rugby football sport ball tackle",
	"🏓": "ping pong table tennis sport",
	"🏸": "badminton sport racket shuttlecock",
	"🥏": "frisbee disc flying sport",
	"🏹": "archery bow arrow sport target",
	"🎣": "fishing pole rod hobby sport",
	"🥊": "boxing glove fight sport punch",
	"🥋": "martial arts karate judo sport",
	"🛹": "skateboard skate sport board trick",
	"🛼": "roller skate sport wheels",
	"⛸️": "ice skate skating winter sport",
	"🎿": "ski skiing winter sport snow",
	"🏂": "snowboard winter sport snow",
	"🏋️": "weight lifting gym workout fitness strength",
	"🧘": "yoga meditation pose mindfulness relax zen",
	"🏊": "swimming pool water sport exercise",
	"🚴": "cycling bike bicycle ride cardio exercise",
	"🧗": "climbing climb rock mountain sport",
	"🎪": "circus tent clown show entertainment",
	"🎭": "performing arts theater drama mask acting",
	"🎨": "art artist paint palette creative draw",
	"🎬": "clapper board movie film cinema director",
	"🎤": "microphone sing karaoke music performance",
	"🎧": "headphone music listen audio sound",
	"🎼": "musical score sheet music notes",
	"🎹": "musical keyboard piano instrument music",
	"🥁": "drum percussion instrument music beat",
	"🎷": "saxophone sax instrument jazz music",
	"🎺": "trumpet brass instrument music jazz",
	"🎸": "guitar instrument music rock strings",
	"🎻": "violin fiddle instrument music classical",
	"🎲": "dice game gambling random chance",
	"🎯": "direct hit target bullseye goal aim",
	"🎮": "video game controller gaming play",
	"🧩": "puzzle piece jigsaw game brain",

	// Objects
	"📱": "mobile phone smartphone cell device",
	"💻": "laptop computer notebook work tech code",
	"⌨️": "keyboard typing computer input",
	"🖥️": "desktop computer monitor screen workstation",
	"🖨️": "printer print document office",
	"🖱️": "computer mouse click pointer",
	"⌚": "watch time clock wrist wearable",
	"⏰": "alarm clock time wake reminder morning",
	"⏱️": "stopwatch timer time measure",
	"📷": "camera photo picture photography",
	"📸": "camera flash photo picture",
	"📹": "video camera recording film",
	"📞": "telephone receiver phone call",
	"☎️": "telephone phone call landline",
	"📺": "television tv screen watch",
	"📻": "radio music news broadcast",
	"🔋": "battery power energy charge",
	"💡": "light bulb idea bright lamp",
	"🔦": "flashlight torch light dark",
	"🕯️": "candle light flame wax romantic",
	"💰": "money bag cash wealth rich dollars",
	"💳": "credit card payment finance bank money",
	"💎": "gem stone diamond jewel precious",
	"🔧": "wrench tool fix repair mechanic",
	"🔨": "hammer tool nail build carpenter",
	"🛠️": "hammer wrench tools fix build repair",
	"⚙️": "gear cog settings mechanical",
	"🔑": "key lock unlock security access",
	"🚪": "door entry exit open close",
	"🛏️": "bed sleep rest bedroom furniture",
	"🛋️": "couch sofa furniture living room",
	"🪑": "chair seat furniture sit",
	"🧸": "teddy bear toy plush cute",
	"🎁": "gift present wrapped birthday celebration",
	"🎈": "balloon party celebration birthday",
	"🎉": "party popper celebration confetti fun",
	"🎊": "confetti ball party celebration",
	"✉️": "envelope letter mail email message",
	"📧": "email letter message electronic mail",
	"📦": "package box parcel delivery shipping",
	"📋": "clipboard document checklist task",
	"📁": "folder file directory organize",
	"📂": "open folder file directory",
	"📅": "calendar date schedule plan event day",
	"📆": "tear-off calendar date schedule",
	"📊": "bar chart data graph statistics analytics",
	"📈": "chart increasing growth up progress success",
	"📉": "chart decreasing down decline loss",
	"📝": "memo note writing document pencil",
	"✏️": "pencil write draw sketch edit",
	"🖊️": "pen write ballpoint ink",
	"📚": "books stack library reading study education",
	"📖": "open book reading study learn literature",
	"📓": "notebook note journal write",
	"📔": "notebook decorative journal write",
	"✂️": "scissors cut snip tool",
	"🔍": "magnifying glass tilted left search find",
	"🔎": "magnifying glass tilted right search find",
	"🔒": "locked secure padlock closed",
	"🔓": "unlocked open padlock accessible",

	// Symbols & Signs
	"✅": "check mark button done complete task yes",
	"❌": "cross mark x no wrong cancel delete",
	"⭕": "hollow red circle o mark",
	"❗": "exclamation mark warning important",
	"❓": "question mark ask wonder query",
	"⚠️": "warning caution alert danger attention",
	"🚫": "prohibited forbidden no banned not allowed",
	"♻️": "recycling symbol recycle green environment",
	"💯": "hundred points perfect score full",
	"🔴": "red circle dot color",
	"🟠": "orange circle dot color",
	"🟡": "yellow circle dot color",
	"🟢": "green circle dot color",
	"🔵": "blue circle dot color",
	"🟣": "purple circle dot color",
	"⚫": "black circle dot color",
	"⚪": "white circle dot color",
	"▶️": "play button start video audio",
	"⏸️": "pause button stop wait video",
	"⏹️": "stop button end quit video",
	"⏭️": "next track button skip forward",
	"⏮️": "last track button skip back",
	"⏩": "fast-forward button speed quick",
	"⏪": "fast reverse button rewind back",
	"🔀": "shuffle button random mix",
	"🔁": "repeat button loop again",
	"🔂": "repeat single button loop one",
	"➡️": "right arrow direction forward next",
	"⬅️": "left arrow direction back previous",
	"⬆️": "up arrow direction top increase",
	"⬇️": "down arrow direction bottom decrease",
	"↗️": "up-right arrow diagonal direction",
	"↘️": "down-right arrow diagonal direction",
	"↙️": "down-left arrow diagonal direction",
	"↖️": "up-left arrow diagonal direction",
	"🔼": "up button arrow increase",
	"🔽": "down button arrow decrease",
	"➕": "plus math add increase more",
	"➖": "minus math subtract decrease less",
	"✖️": "multiply math times cross",
	"➗": "divide math division split",
	"💲": "dollar sign money currency usd",
	"©️": "copyright symbol legal",
	"®️": "registered trademark legal",
	"™️": "trade mark symbol legal brand",

	// Weather & Nature
	"☀️": "sun sunny weather hot day bright morning",
	"🌤️": "sun behind small cloud partly sunny",
	"⛅": "sun behind cloud partly cloudy",
	"☁️": "cloud cloudy weather overcast",
	"🌧️": "cloud with rain rainy weather",
	"⛈️": "cloud with lightning thunder storm",
	"🌨️": "cloud with snow snowy weather",
	"❄️": "snowflake snow winter cold ice",
	"☃️": "snowman snow winter cold",
	"⛄": "snowman without snow winter",
	"💨": "dashing away wind fast speed",
	"💧": "droplet water liquid wet",
	"💦": "sweat droplets water splash",
	"☔": "umbrella with rain drops weather",
	"🌊": "water wave ocean sea surf",
	"🌪️": "tornado cyclone storm weather",
	"🌈": "rainbow colors weather after rain",
	"🌙": "crescent moon night sleep evening dark",
	"⭐": "star night space twinkle",
	"🌟": "glowing star sparkle shine bright",
	"✨": "sparkles shiny stars magic glitter",
	"⚡": "high voltage lightning bolt electric",
	"🔥": "fire flame hot burn heat",
	"💥": "collision explosion boom bang",
	"🌍": "globe earth world europe africa",
	"🌎": "globe earth world americas",
	"🌏": "globe earth world asia australia",
	"🌐": "globe meridians internet world wide web",
	"🗺️": "world map geography travel navigation",
}
